// <auto-generated />
using System;
using FlightPrep.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightPrep.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408212746_MaxLengthLimit")]
    partial class MaxLengthLimit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightPrep.Domain.Models.Balloon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("BasketWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("BurnerWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("CylindersWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("EnvelopeOnlyWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("InternalEnvelopeTempC")
                        .HasColumnType("double precision");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("VolumeM3")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Balloons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            InternalEnvelopeTempC = 80.0,
                            Registration = "OO-BUT",
                            Type = "BB22N",
                            VolumeM3 = 2200.0
                        });
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlightPreparationId", "Section", "Order");

                    b.ToTable("FlightImages");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightPreparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualFlightDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ActualLandingNotes")
                        .HasColumnType("text");

                    b.Property<string>("ActualRemarks")
                        .HasColumnType("text");

                    b.Property<bool>("BallonVisueel")
                        .HasColumnType("boolean");

                    b.Property<string>("Ballonbulletin")
                        .HasColumnType("text");

                    b.Property<int?>("BalloonId")
                        .HasColumnType("integer");

                    b.Property<string>("Beperkingen")
                        .HasColumnType("text");

                    b.Property<bool>("BranderGetest")
                        .HasColumnType("boolean");

                    b.Property<double?>("CapeJkg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<double?>("CylindersWeightKg")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<double?>("DauwpuntC")
                        .HasColumnType("double precision");

                    b.Property<string>("EhboEnBlusser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("EnvelopeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("FuelAvailableMinutes")
                        .HasColumnType("integer");

                    b.Property<double?>("FuelConsumptionL")
                        .HasColumnType("double precision");

                    b.Property<int?>("FuelRequiredMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("GasflaconsGecontroleerd")
                        .HasColumnType("boolean");

                    b.Property<bool>("InstrumentenWerkend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlown")
                        .HasColumnType("boolean");

                    b.Property<string>("KmlTrack")
                        .HasColumnType("text");

                    b.Property<string>("LandingLocationText")
                        .HasColumnType("text");

                    b.Property<double?>("LiftUnits")
                        .HasColumnType("double precision");

                    b.Property<string>("LoadNotes")
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Luchtruimstructuur")
                        .HasColumnType("text");

                    b.Property<int?>("MaxAltitudeFt")
                        .HasColumnType("integer");

                    b.Property<string>("Metar")
                        .HasColumnType("text");

                    b.Property<string>("Neerslag")
                        .HasColumnType("text");

                    b.Property<string>("NotamsGecontroleerd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("OFPBasketWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("OFPBurnerWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("OFPEnvelopeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Obstakels")
                        .HasColumnType("text");

                    b.Property<string>("OperatorName")
                        .HasColumnType("text");

                    b.Property<string>("PassagierslijstIngevuld")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaxBriefing")
                        .HasColumnType("text");

                    b.Property<double?>("PicWeightKg")
                        .HasColumnType("double precision");

                    b.Property<int?>("PilotId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("PlannedLandingTime")
                        .HasColumnType("time without time zone");

                    b.Property<double?>("QnhHpa")
                        .HasColumnType("double precision");

                    b.Property<int?>("SurfaceWindDirectionDeg")
                        .HasColumnType("integer");

                    b.Property<double?>("SurfaceWindSpeedKt")
                        .HasColumnType("double precision");

                    b.Property<string>("Taf")
                        .HasColumnType("text");

                    b.Property<double?>("TemperatuurC")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("Tijdstip")
                        .HasColumnType("time without time zone");

                    b.Property<double?>("TotaalLiftKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Traject")
                        .HasColumnType("text");

                    b.Property<string>("TrajectorySimulationJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VeldEigenaarGemeld")
                        .HasColumnType("boolean");

                    b.Property<bool>("VerankeringenGecontroleerd")
                        .HasColumnType("boolean");

                    b.Property<bool?>("VisibleDefects")
                        .HasColumnType("boolean");

                    b.Property<string>("VisibleDefectsNotes")
                        .HasColumnType("text");

                    b.Property<string>("VluchtplanIngediend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WindPerHoogte")
                        .HasColumnType("text");

                    b.Property<double?>("ZichtbaarheidKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BalloonId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PilotId");

                    b.ToTable("FlightPreparations");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightPreparationShare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SharedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SharedWithUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SharedWithUserId");

                    b.HasIndex("FlightPreparationId", "SharedWithUserId")
                        .IsUnique();

                    b.ToTable("FlightPreparationShares");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.GoNoGoSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapeRedJkg")
                        .HasColumnType("double precision");

                    b.Property<double>("CapeYellowJkg")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<double>("VisRedKm")
                        .HasColumnType("double precision");

                    b.Property<double>("VisYellowKm")
                        .HasColumnType("double precision");

                    b.Property<double>("WindRedKt")
                        .HasColumnType("double precision");

                    b.Property<double>("WindYellowKt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("GoNoGoSettings");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirspaceNotes")
                        .HasColumnType("text");

                    b.Property<double?>("ElevationM")
                        .HasColumnType("double precision");

                    b.Property<string>("IcaoCode")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.LoginEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("Timestamp");

                    b.ToTable("LoginEvents");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.OFPSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("PassengerEquipmentWeightKg")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("OfpSettings");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsChild")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTransport")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NeedsAssistance")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlightPreparationId", "Order");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .HasColumnType("text");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.WindLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AltitudeFt")
                        .HasColumnType("integer");

                    b.Property<int?>("DirectionDeg")
                        .HasColumnType("integer");

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeedKt")
                        .HasColumnType("integer");

                    b.Property<double?>("TempC")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlightPreparationId", "Order");

                    b.ToTable("WindLevels");
                });

            modelBuilder.Entity("FlightPrep.Infrastructure.Data.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("OperatorName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Balloon", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightImage", b =>
                {
                    b.HasOne("FlightPrep.Domain.Models.FlightPreparation", "FlightPreparation")
                        .WithMany("Images")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPreparation");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightPreparation", b =>
                {
                    b.HasOne("FlightPrep.Domain.Models.Balloon", "Balloon")
                        .WithMany()
                        .HasForeignKey("BalloonId");

                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlightPrep.Domain.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("FlightPrep.Domain.Models.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId");

                    b.Navigation("Balloon");

                    b.Navigation("Location");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightPreparationShare", b =>
                {
                    b.HasOne("FlightPrep.Domain.Models.FlightPreparation", null)
                        .WithMany("Shares")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("SharedWithUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.GoNoGoSettings", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Location", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.OFPSettings", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Passenger", b =>
                {
                    b.HasOne("FlightPrep.Domain.Models.FlightPreparation", "FlightPreparation")
                        .WithMany("Passengers")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPreparation");
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.Pilot", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.WindLevel", b =>
                {
                    b.HasOne("FlightPrep.Domain.Models.FlightPreparation", "FlightPreparation")
                        .WithMany("WindLevels")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPreparation");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("FlightPrep.Infrastructure.Data.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlightPrep.Domain.Models.FlightPreparation", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Passengers");

                    b.Navigation("Shares");

                    b.Navigation("WindLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
