// <auto-generated />
using System;
using FlightPrep.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightPrep.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331063314_ReplaceBalloonVolumeWithDouble")]
    partial class ReplaceBalloonVolumeWithDouble
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightPrep.Models.Balloon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double?>("EmptyWeightKg")
                        .HasColumnType("double precision");

                    b.Property<double?>("InternalEnvelopeTempC")
                        .HasColumnType("double precision");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("VolumeM3")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Balloons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmptyWeightKg = 323.39999999999998,
                            InternalEnvelopeTempC = 80.0,
                            Registration = "OO-BUT",
                            Type = "BB22N",
                            VolumeM3 = 2200.0
                        });
                });

            modelBuilder.Entity("FlightPrep.Models.FlightImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FlightPreparationId", "Section", "Order");

                    b.ToTable("FlightImages");
                });

            modelBuilder.Entity("FlightPrep.Models.FlightPreparation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualFlightDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ActualLandingNotes")
                        .HasColumnType("text");

                    b.Property<string>("ActualRemarks")
                        .HasColumnType("text");

                    b.Property<bool>("BallonVisueel")
                        .HasColumnType("boolean");

                    b.Property<string>("Ballonbulletin")
                        .HasColumnType("text");

                    b.Property<int?>("BalloonId")
                        .HasColumnType("integer");

                    b.Property<string>("Beperkingen")
                        .HasColumnType("text");

                    b.Property<bool>("BranderGetest")
                        .HasColumnType("boolean");

                    b.Property<double?>("CapeJkg")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("date");

                    b.Property<double?>("DauwpuntC")
                        .HasColumnType("double precision");

                    b.Property<string>("EhboEnBlusser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("EnvelopeWeightKg")
                        .HasColumnType("double precision");

                    b.Property<bool>("GasflaconsGecontroleerd")
                        .HasColumnType("boolean");

                    b.Property<bool>("InstrumentenWerkend")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFlown")
                        .HasColumnType("boolean");

                    b.Property<string>("KmlTrack")
                        .HasColumnType("text");

                    b.Property<double?>("LiftUnits")
                        .HasColumnType("double precision");

                    b.Property<string>("LoadNotes")
                        .HasColumnType("text");

                    b.Property<int?>("LocationId")
                        .HasColumnType("integer");

                    b.Property<string>("Luchtruimstructuur")
                        .HasColumnType("text");

                    b.Property<int?>("MaxAltitudeFt")
                        .HasColumnType("integer");

                    b.Property<string>("Metar")
                        .HasColumnType("text");

                    b.Property<string>("Neerslag")
                        .HasColumnType("text");

                    b.Property<string>("NotamsGecontroleerd")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Obstakels")
                        .HasColumnType("text");

                    b.Property<string>("PassagierslijstIngevuld")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaxBriefing")
                        .HasColumnType("text");

                    b.Property<int?>("PilotId")
                        .HasColumnType("integer");

                    b.Property<double?>("QnhHpa")
                        .HasColumnType("double precision");

                    b.Property<int?>("SurfaceWindDirectionDeg")
                        .HasColumnType("integer");

                    b.Property<double?>("SurfaceWindSpeedKt")
                        .HasColumnType("double precision");

                    b.Property<string>("Taf")
                        .HasColumnType("text");

                    b.Property<double?>("TemperatuurC")
                        .HasColumnType("double precision");

                    b.Property<TimeOnly>("Tijdstip")
                        .HasColumnType("time without time zone");

                    b.Property<double?>("TotaalLiftKg")
                        .HasColumnType("double precision");

                    b.Property<string>("Traject")
                        .HasColumnType("text");

                    b.Property<string>("TrajectorySimulationJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("VeldEigenaarGemeld")
                        .HasColumnType("boolean");

                    b.Property<bool>("VerankeringenGecontroleerd")
                        .HasColumnType("boolean");

                    b.Property<string>("VluchtplanIngediend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WindPerHoogte")
                        .HasColumnType("text");

                    b.Property<double?>("ZichtbaarheidKm")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("BalloonId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PilotId");

                    b.ToTable("FlightPreparations");
                });

            modelBuilder.Entity("FlightPrep.Models.GoNoGoSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("CapeRedJkg")
                        .HasColumnType("double precision");

                    b.Property<double>("CapeYellowJkg")
                        .HasColumnType("double precision");

                    b.Property<double>("VisRedKm")
                        .HasColumnType("double precision");

                    b.Property<double>("VisYellowKm")
                        .HasColumnType("double precision");

                    b.Property<double>("WindRedKt")
                        .HasColumnType("double precision");

                    b.Property<double>("WindYellowKt")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("GoNoGoSettings");
                });

            modelBuilder.Entity("FlightPrep.Models.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AirspaceNotes")
                        .HasColumnType("text");

                    b.Property<double?>("ElevationM")
                        .HasColumnType("double precision");

                    b.Property<string>("IcaoCode")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("FlightPrep.Models.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<double>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlightPreparationId", "Order");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("FlightPrep.Models.Pilot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("WeightKg")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Pilots");
                });

            modelBuilder.Entity("FlightPrep.Models.WindLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AltitudeFt")
                        .HasColumnType("integer");

                    b.Property<int?>("DirectionDeg")
                        .HasColumnType("integer");

                    b.Property<int>("FlightPreparationId")
                        .HasColumnType("integer");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("SpeedKt")
                        .HasColumnType("integer");

                    b.Property<double?>("TempC")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FlightPreparationId", "Order");

                    b.ToTable("WindLevels");
                });

            modelBuilder.Entity("FlightPrep.Models.FlightImage", b =>
                {
                    b.HasOne("FlightPrep.Models.FlightPreparation", "FlightPreparation")
                        .WithMany("Images")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPreparation");
                });

            modelBuilder.Entity("FlightPrep.Models.FlightPreparation", b =>
                {
                    b.HasOne("FlightPrep.Models.Balloon", "Balloon")
                        .WithMany()
                        .HasForeignKey("BalloonId");

                    b.HasOne("FlightPrep.Models.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.HasOne("FlightPrep.Models.Pilot", "Pilot")
                        .WithMany()
                        .HasForeignKey("PilotId");

                    b.Navigation("Balloon");

                    b.Navigation("Location");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("FlightPrep.Models.Passenger", b =>
                {
                    b.HasOne("FlightPrep.Models.FlightPreparation", "FlightPreparation")
                        .WithMany("Passengers")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPreparation");
                });

            modelBuilder.Entity("FlightPrep.Models.WindLevel", b =>
                {
                    b.HasOne("FlightPrep.Models.FlightPreparation", "FlightPreparation")
                        .WithMany("WindLevels")
                        .HasForeignKey("FlightPreparationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightPreparation");
                });

            modelBuilder.Entity("FlightPrep.Models.FlightPreparation", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Passengers");

                    b.Navigation("WindLevels");
                });
#pragma warning restore 612, 618
        }
    }
}
